### ISSUE TITLE
Unimplemented system channels

### ISSUE THREAD

**Issue by bbrto21** [flutter-tizen/embedder#11]
Below are the channels implemented in Android but not implemented in Tizen.
These should be reviewed and implemented.

- [x] flutter/accessibility: flutter-tizen/flutter-tizen/issues/151
- [x] flutter/deferredcomponent: not applicable
- [x] flutter/mousecursor: https://github.com/flutter-tizen/embedder/pull/32
- [x] flutter/restoration: not generally applicable
- [x] flutter/system: not needed (FlutterEngineNotifyLowMemoryWarning)
- [ ] flutter/platform: has unimplemented methods
  - ~[SystemChrome.setApplicationSwitcherDescription](https://api.flutter.dev/flutter/services/SystemChrome/setApplicationSwitcherDescription.html)~ (not supported)
  - [SystemChrome.setEnabledSystemUIMode](https://api.flutter.dev/flutter/services/SystemChrome/setEnabledSystemUIMode.html) (see https://github.com/flutter-tizen/engine/pull/207)
  - ~[SystemChrome.setSystemUIOverlayStyle](https://api.flutter.dev/flutter/services/SystemChrome/setSystemUIOverlayStyle.html)~  (not supported)

**Comment by swift-kim** [comment]
The restoration channel is not applicable for Tizen because there's nothing on Tizen that corresponds to Android's `onSaveInstanceState` or iOS's `encodeRestorableStateWithCoder`. (Note: `OnPause` or `OnDestroy` has [nothing to do](https://developer.android.com/reference/android/app/Activity#onSaveInstanceState(android.os.Bundle)) with state restoration.)

Brief overview of how restoration works on Android:
- The framework always stores the latest copy of restoration data to the platform thread (through the restoration channel).
- When `onSaveInstanceState` is called, it synchronously retrieves the stored data and saves them to a bundle.
- When `onRestoreInstanceState` is called, the restoration data are read from the bundle passed by the platform and `RestorationChannel` stores them until they are requested by the framework.
